#!/system/bin/sh

#
## Added by urain39@cyfan.cf
#

TOPDIR="/data/media/0"
TMPDIRS="$TOPDIR/ramdisk"

[ -f /data/tmpdir.conf ] && . /data/tmpdir.conf


IFS=$'\n'
for TMPDIR in $TMPDIRS; do
    TLEN=${#TOPDIR}
    TMPDIR="$(realpath "$TMPDIR")"
    if [ "${TMPDIR:0:$TLEN}" == "$TOPDIR" ]; then
        mkdir -p "$TMPDIR"
        mount -t tmpfs tmpfs "$TMPDIR"
    fi
done
