#!/system/bin/sh

#
## Added by urain39@cyfan.cf
#

TOPDIR="/data/media/0"
TMPDIRS="$TOPDIR/ramdisk"

[ -f /data/tmpdir.conf ] && TMPDIRS="$(sed "/^[\t ]*#/d;s:\\\$TOPDIR:$TOPDIR:g" /data/tmpdir.conf)"

IFS=$'\n'
for TMPDIR in $TMPDIRS; do
    TLEN=${#TOPDIR}
    echo "$TMPDIR" | grep -Eq '^([\\\/]([^\\\/\.]{1,2}|[^\\\/]{3,}))*[\\\/]?$'
    if [ $? = 0 ] && [ "${TMPDIR:0:$TLEN}" == "$TOPDIR" ]; then
        mkdir -p "$TMPDIR"
        mount -t tmpfs tmpfs -o size=25% "$TMPDIR"
    fi
done
