#!/system/bin/sh

{
  while sleep 15; do
    chmod 644 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
    chmod 444 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
  done
} &
