# Added by urain39@cyfan.cf

# Dirty ratio
vm.dirty_background_ratio = 50

# Absolutely dirty ratio
vm.dirty_ratio = 80

# Writeback time of dirty page(1/100s)
vm.dirty_writeback_centisecs = 6000

# Expire time of dirty page(1/100s)
vm.dirty_expire_centisecs = 30000

# VFS cache pressure(default: 100)
vm.vfs_cache_pressure = 50
