# Default
$TOPDIR/ramdisk

# Coolapk
$TOPDIR/Android/data/com.coolapk.market/cache
$TOPDIR/Android/data/com.coolapk.market/files/tencent
$TOPDIR/Android/data/com.coolapk.market/files/TTCache

# MT Manager
$TOPDIR/MT2
$TOPDIR/Android/data/bin.mt.plus/cache
$TOPDIR/Android/data/bin.mt.plus/temp

# Netease Common
$TOPDIR/netease/adcache

# Netease Music
$TOPDIR/netease/cloudmusic/Cache

# Thunder (Xunlei)
$TOPDIR/Android/data/com.xunlei.downloadprovider/cache
$TOPDIR/Android/data/com.xunlei.downloadprovider/cachett_ad
$TOPDIR/Android/data/com.xunlei.downloadprovider/files/apk
$TOPDIR/Android/data/com.xunlei.downloadprovider/files/MqttConnection
$TOPDIR/Android/data/com.xunlei.downloadprovider/files/TTCache

# TIM
$TOPDIR/Android/data/com.tencent.tim/cache

# Bilibili
$TOPDIR/Android/data/tv.danmaku.bili/cache

# OneDrive
$TOPDIR/Android/data/com.microsoft.skydrive/cache

# QuickPic
$TOPDIR/Android/data/com.alensw.PicFolder/cache

# MX Player
$TOPDIR/Android/data/com.mxtech.videoplayer.ad/cache
